import Constantes.Constantes as Const


OWA_BBT = [0.5, 0.3, 0.1, 0.05, 0.05]
PENALIZATION_VALUE_BLOCK_DROP = 0.15
PENALIZATION_VALUE_INCORRECT_MOVEMENT = 0.1


FATIGUE_METRICS_BBT = [
    Const.FATIGUE_STRENGTH, 
    Const.FATIGUE_TIME,
    Const.FATIGUE_VELOCITY, 
    Const.FATIGUE_HAND_TRAJECTORY,
    Const.FATIGUE_HEADPOSITION
]
FATIGUE_PENALIZATIONS_BBT = {
    Const.PENALIZATION_BLOCK_DROP: PENALIZATION_VALUE_BLOCK_DROP,
    Const.PENALIZATION_INCORRECT_MOVEMENT: PENALIZATION_VALUE_INCORRECT_MOVEMENT
}

BBT_DURATION = 60    #Seconds