PORCENTAJE_COMPARACION = 20
MAXIMO_FICHEROS_HISTORICOS = 50
LEER_FICHEROS_OCULUS = False

DIRECTORIO_FICHEROS_GENERADOS_OCULUS = "/sdcard/Android/data/com.RehabImmersive.BBT_2023_12_BodyCalibration/BoxAndBlock"
DIRECTORIO_FICHEROS_GENERADOS_LOCAL = "RI_Data"
DIRECTORIO_HISTORICAL = "Historical.csv"
DIRECTORIO_TRACKING_DATA = "/TrackingData/"
PREFIJO_FICHEROS = "OculusTracking_"
EXTENSION_FICHEROS = ".csv"
DIRECTORIO_UTILIZADO = '' #No modificar



