PORCENTAJE_COMPARACION = 20
MAXIMO_FICHEROS_HISTORICOS = 50
LEER_FICHEROS_OCULUS = True

DIRECTORIO_FICHEROS_GENERADOS_OCULUS = "/sdcard/Android/data/com.RehabImmersive.BoxAndBlock/BoxAndBlock/"
DIRECTORIO_FICHEROS_GENERADOS_LOCAL = "/CSVs/"
DIRECTORIO_UTILIZADO = ''
DIRECTORIO_HISTORICAL = "Historical.csv"
DIRECTORIO_TRACKING_DATA = "/TrackingData/"
PREFIJO_FICHEROS = "OculusTracking_"
EXTENSION_FICHEROS = ".csv"


RUTA_CARPETA_SALIDA = "Output_fatigue/"
RUTA_CARPETA_JSON = "Jsons/" 
RUTA_CSV = "output.csv"
