### COLUMNAS FICHERO DE SALIDA
OUTPUT_DATE = 'DATE'
OUTPUT_USER = 'USER'
OUTPUT_FATIGUE_VALUE = 'FATIGUE VALUE'
OUTPUT_FATIGUE_CLASIFICATION = 'FATIGUE CLASSIFICATION'
OUTPUT_INDEX = 'INDEX'

OUTPUT_REPETITIONS = 'Repetitions'
OUTPUT_NUMREPETITION = 'Repetition number'
OUTPUT_FATIGUE_REPETITION = 'Repetition Fatigue'
OUTPUT_FATIGUE_METRICS = 'Fatigue per metric'
OUTPUT_WARNINGS = 'Fatigue warnings'
OUTPUT_INICIO_SEG = 'Inicio_Seg'
OUTPUT_FINAL_SEG = 'Final_Seg'


OUTPUT_FOLDER = "Output_fatigue/"
OUTPUT_JSON_FOLDER = "Jsons/" 
CSV_NAME = "output.csv"