#Juegos
JUEGO_BBT = 'BoxAndBlock'

#Clasificación de la fatiga
FATIGA_LOW = 'LOW'
FATIGA_MODERATE = 'MODERATE'
FATIGA_HIGH = 'HIGH'
FATIGA_VERY_HIGH = 'VERY HIGH'


## FATIGAS
FATIGUE_WRIST = 'Wrist Fatigue'
FATIGUE_STRENGTH = 'Strength Fatigue'
FATIGUE_TIME = 'Time Fatigue'
FATIGUE_VELOCITY = 'Velocity Fatigue'
FATIGUE_HEADPOSITION = 'HeadPosition Fatiga'
FATIGUE_HAND_TRAJECTORY = 'Hand Trajectory Fatigue'
PENALIZATION_BLOCK_DROP = 'Block Drop Penalization'
PENALIZATION_INCORRECT_MOVEMENT = 'Incorrect movement Penalization'

#
INICIO_REPES = 1
ABNORMAL_FATIGUE = 0.7


#AUXILIARES
HEADPOSITION_MAX_X = 'MAX_HEADPOSITION_X'
HEADPOSITION_MIN_X = 'MIN_HEADPOSITION_X'
HEADPOSITION_MAX_Y = 'MAX_HEADPOSITION_Y'
HEADPOSITION_MIN_Y = 'MIN_HEADPOSITION_Y'
HEADPOSITION_MAX_Z = 'MAX_HEADPOSITION_Z'
HEADPOSITION_MIN_Z = 'MIN_HEADPOSITION_Z'

CURVATURA_TOMAR_BLOQUE_Y = 'Take_block_y'
CURVATURA_PUNTO_MAS_ALTO_Y = 'Highest_Point_Y'
CURVATURA_SOLTAR_BLOQUE_X = 'Leave_block_x'
CURVATURA_SOLTAR_BLOQUE_Y = 'Leave_block_y'



## COLUMNAS CSV
FRAME = 'Frame'
TIME = 'Time'
HEADPOSITION_X = 'HeadPosition_x'
HEADPOSITION_Y = 'HeadPosition_y'
HEADPOSITION_Z = 'HeadPosition_z'
HEADROTATION_X = 'HeadRotation_x'
HEADROTATION_Y = 'HeadRotation_y'
HEADROTATION_Z = 'HeadRotation_z'
HANDDETECTED = 'HandDetected'
HIGHCONFIDENCE = 'HighConfidence'
HANDPOSITION_X = 'HandPosition_x'
HANDPOSITION_Y = 'HandPosition_y'
HANDPOSITION_Z = 'HandPosition_z'
HANDROTATION_X = 'HandRotation_x'
HANDROTATION_Y = 'HandRotation_y'
HANDROTATION_Z = 'HandRotation_z'
HANDVELOCITY_X = 'HandVelocity_x'
HANDVELOCITY_Y = 'HandVelocity_y'
HANDVELOCITY_Z = 'HandVelocity_z'
WRISTTWIST = 'WristTwist'
ISPINCHGRABBING = 'IsPinchGrabbing'
ISPALMGRABBING = 'IsPalmGrabbing'
ISAUTOGRIPGRABBING = 'IsAutogripGrabbing'
STRENGTHTHUMBINDEX = 'StrengthThumbIndex'
STRENGTHTHUMB_MIDDLE = 'StrengthThumbMiddle'
STRENGTHTHUMB_RING = 'StrengthThumbRing'
STRENGTHTHUMB_PINKY = 'StrengthThumbPinky'
STRENGTHPALM_INDEX = 'StrengthPalmIndex'
STRENGTHPALM_MIDDLE = 'StrengthPalmMiddle'
STRENGTHPALM_RING = 'StrengthPalmRing'
STRENGTHPALM_PINKY = 'StrengthPalmPinky'
GRABIDENTIFIER = 'GrabIdentifier'
MOVEDCORRECTLY = 'MovedCorrectly'
NUMREPETICION = 'NumRepeticion'
HIST_DATE = "DATE"
HIST_GAME = "GAME"
HIST_USER = "USER"













