#Juegos
JUEGO_BBT = 'BoxAndBlock'

#Clasificación de la fatiga
FATIGA_LOW = 'LOW'
FATIGA_MODERATE = 'MODERATE'
FATIGA_HIGH = 'HIGH'
FATIGA_VERY_HIGH = 'VERY HIGH'



## COLUMNAS CSV
FRAME = 'Frame'
TIME = 'Time'
HEADPOSITION_X = 'HeadPosition_x'
HEADPOSITION_Y = 'HeadPosition_y'
HEADPOSITION_Z = 'HeadPosition_z'
HEADROTATION_X = 'HeadRotation_x'
HEADROTATION_Y = 'HeadRotation_y'
HEADROTATION_Z = 'HeadRotation_z'
HANDDETECTED = 'HandDetected'
HIGHCONFIDENCE = 'HighConfidence'
HANDPOSITION_X = 'HandPosition_x'
HANDPOSITION_Y = 'HandPosition_y'
HANDPOSITION_Z = 'HandPosition_z'
HANDROTATION_X = 'HandRotation_x'
HANDROTATION_Y = 'HandRotation_y'
HANDROTATION_Z = 'HandRotation_z'
HANDVELOCITY_X = 'HandVelocity_x'
HANDVELOCITY_Y = 'HandVelocity_y'
HANDVELOCITY_Z = 'HandVelocity_z'
WRISTTWIST = 'WristTwist'
ISPINCHGRABBING = 'IsPinchGrabbing'
ISPALMGRABBING = 'IsPalmGrabbing'
ISAUTOGRIPGRABBING = 'IsAutogripGrabbing'
STRENGTHTHUMBINDEX = 'StrengthThumbIndex'
STRENGTHTHUMB_MIDDLE = 'StrengthThumbMiddle'
STRENGTHTHUMB_RING = 'StrengthThumbRing'
STRENGTHTHUMB_PINKY = 'StrengthThumbPinky'
STRENGTHPALM_INDEX = 'StrengthPalmIndex'
STRENGTHPALM_MIDDLE = 'StrengthPalmMiddle'
STRENGTHPALM_RING = 'StrengthPalmRing'
STRENGTHPALM_PINKY = 'StrengthPalmPinky'
GRABIDENTIFIER = 'GrabIdentifier'
MOVEDCORRECTLY = 'MovedCorrectly'
NUMREPETICION = 'NumRepeticion'
HIST_DATE = "DATE"
HIST_GAME = "GAME"
HIST_USER = "USER"
## FATIGAS
FATIGA_WRIST = 'Fatiga Wrist'
FATIGA_STRENGTH = 'Fatiga Strength'
FATIGA_TIEMPO = 'Fatiga Tiempo'
FATIGA_VELOCIDAD = 'Fatiga Velocidad'
FATIGA_HEADPOSITION = 'Fatiga HeadPosition'
FATIGA_CURVATURA_MANO = 'Fatiga Curvatura Trayectoria Mano'
PENALIZACION_NUM_CAIDAS_BLOQUE = 'Penalizacion Caidas del Bloque'
PENALIZACION_MOVIMIENTO_INCORRECTO = 'Penalizacion Movimiento Incorrecto'

### PESOS OWA
OWA_TIEMPO = 0.2
OWA_VELOCIDAD = 0.1
OWA_HEADPOSITION = 0.2
OWA_STRENGTH = 0.3
OWA_CURVATURA_MANO = 0.2
VALOR_PENALIZACION_CAIDA_DEL_BLOQUE = 0.15
VALOR_PENALIZACION_MOVIMIENTO_INCORRECTO = 0.1
#AUXILIARES
HEADPOSITION_MAX_X = 'MAX_HEADPOSITION_X'
HEADPOSITION_MIN_X = 'MIN_HEADPOSITION_X'
HEADPOSITION_MAX_Y = 'MAX_HEADPOSITION_Y'
HEADPOSITION_MIN_Y = 'MIN_HEADPOSITION_Y'
HEADPOSITION_MAX_Z = 'MAX_HEADPOSITION_Z'
HEADPOSITION_MIN_Z = 'MIN_HEADPOSITION_Z'

CURVATURA_TOMAR_BLOQUE_Y = 'Tomar_Bloque_Y'
CURVATURA_PUNTO_MAS_ALTO_Y = 'Punto_Mas_Alto_Y_Ida'
CURVATURA_SOLTAR_BLOQUE_X = 'Soltar_Bloque_X'
CURVATURA_SOLTAR_BLOQUE_Y = 'Soltar_Bloque_Y'

INICIO_REPES = 1


#### METRICAS DE FATIGA
## BBT
METRICAS_FATIGA_BBT = {
    FATIGA_STRENGTH: OWA_STRENGTH, 
    FATIGA_TIEMPO: OWA_TIEMPO,
    FATIGA_VELOCIDAD: OWA_VELOCIDAD, 
    FATIGA_CURVATURA_MANO: OWA_CURVATURA_MANO,
    FATIGA_HEADPOSITION: OWA_HEADPOSITION,
}
PENALIZACIONES_FATIGA_BBT = {
    PENALIZACION_NUM_CAIDAS_BLOQUE: VALOR_PENALIZACION_CAIDA_DEL_BLOQUE,
    PENALIZACION_MOVIMIENTO_INCORRECTO: VALOR_PENALIZACION_MOVIMIENTO_INCORRECTO
}
DURACION_EJERCICIO_BBT = 60    #En segundos
TIEMPO_DESCANSO = "Tiempo Descanso"
MULTIPLICADOR = "Multiplicador"
FATIGA_ACUMULADA = {
    # Tiempo de descanso : Multiplicador de la fatiga anterior
    "Intervalo 1":{
        TIEMPO_DESCANSO: 90,
        MULTIPLICADOR: 50
    },
    "Intervalo 2":{
        TIEMPO_DESCANSO: 180,
        MULTIPLICADOR: 25
    },
    "Intervalo 3":{
        TIEMPO_DESCANSO: 300,
        MULTIPLICADOR: 12.5
    },
}




### COLUMNAS FICHERO DE SALIDA
SALIDA_DATE = 'DATE'
SALIDA_USER = 'USER'
SALIDA_FATIGA_ENTERO = 'VALOR FATIGA'
SALIDA_FATIGA_CLASIFICACION = 'TIPO FATIGA'
SALIDA_INDICE = 'INDICE'

SALIDA_REPETICIONES = 'Repeticiones'
SALIDA_NUMREPETICION = 'Numero repeticion'
SALIDA_FATIGA_REPETICION = 'Fatiga repeticion'
SALIDA_FATIGA_METRICAS = 'Fatiga por metrica'
SALIDA_AVISOS = 'Avisos de fatiga'

