## COLUMNAS CSV
FRAME = 'Frame'
TIME = 'Time'
HEADPOSITION_X = 'HeadPosition_x'
HEADPOSITION_Y = 'HeadPosition_y'
HEADPOSITION_Z = 'HeadPosition_z'
HEADROTATION_X = 'HeadRotation_x'
HEADROTATION_Y = 'HeadRotation_y'
HEADROTATION_Z = 'HeadRotation_z'
HANDDETECTED = 'HandDetected'
HIGHCONFIDENCE = 'HighConfidence'
HANDPOSITION_X = 'HandPosition_x'
HANDPOSITION_Y = 'HandPosition_y'
HANDPOSITION_Z = 'HandPosition_z'
HANDROTATION_X = 'HandRotation_x'
HANDROTATION_Y = 'HandRotation_y'
HANDROTATION_Z = 'HandRotation_z'
HANDVELOCITY_X = 'HandVelocity_x'
HANDVELOCITY_Y = 'HandVelocity_y'
HANDVELOCITY_Z = 'HandVelocity_z'
WRISTTWIST = 'WristTwist'
ISPINCHGRABBING = 'IsPinchGrabbing'
ISPALMGRABBING = 'IsPalmGrabbing'
ISAUTOGRIPGRABBING = 'IsAutogripGrabbing'
STRENGTHTHUMBINDEX = 'StrengthThumbIndex'
STRENGTHTHUMB_MIDDLE = 'StrengthThumbMiddle'
STRENGTHTHUMB_RING = 'StrengthThumbRing'
STRENGTHTHUMB_PINKY = 'StrengthThumbPinky'
STRENGTHPALM_INDEX = 'StrengthPalmIndex'
STRENGTHPALM_MIDDLE = 'StrengthPalmMiddle'
STRENGTHPALM_RING = 'StrengthPalmRing'
STRENGTHPALM_PINKY = 'StrengthPalmPinky'
NUMREPETICION = 'NumRepeticion'


## FATIGAS
FATIGA_WRIST = 'Fatiga Wrist'
FATIGA_STRENGTH = 'Fatiga Strength'
FATIGA_TIEMPO = 'Fatiga Tiempo'
FATIGA_VELOCIDAD = 'Fatiga Velocidad'
FATIGA_HEADPOSITION = 'Fatiga HeadPosition'
FATIGA_CURVATURA_MANO = 'Fatiga Curvatura Trayectoria Mano'

### PESOS OWA
OWA_TIEMPO = 0.05
OWA_VELOCIDAD = 0.1
OWA_HEADPOSITION = 0.2
OWA_STRENGTH = 0.3
OWA_CURVATURA_MANO = 0.35
#AUXILIARES
HEADPOSITION_MAX_X = 'MAX_HEADPOSITION_X'
HEADPOSITION_MIN_X = 'MIN_HEADPOSITION_X'
HEADPOSITION_MAX_Y = 'MAX_HEADPOSITION_Y'
HEADPOSITION_MIN_Y = 'MIN_HEADPOSITION_Y'
HEADPOSITION_MAX_Z = 'MAX_HEADPOSITION_Z'
HEADPOSITION_MIN_Z = 'MIN_HEADPOSITION_Z'

CURVATURA_TOMAR_BLOQUE_Y = 'Tomar_Bloque_Y'
CURVATURA_PUNTO_MAS_ALTO_Y_IDA = 'Punto_Mas_Alto_Y_Ida'
CURVATURA_PUNTO_MAS_ALTO_Y_VUELTA = 'Punto_Mas_Alto_Y_Vuelta'
CURVATURA_SOLTAR_BLOQUE_X = 'Soltar_Bloque_X'
CURVATURA_SOLTAR_BLOQUE_Y = 'Soltar_Bloque_Y'
