## COLUMNAS CSV
FRAME = 'Frame'
TIME = 'Time'
HEADPOSITION_X = 'HeadPosition_x'
HEADPOSITION_Y = 'HeadPosition_y'
HEADPOSITION_Z = 'HeadPosition_z'
HEADROTATION_X = 'HeadRotation_x'
HEADROTATION_Y = 'HeadRotation_y'
HEADROTATION_Z = 'HeadRotation_z'
HANDDETECTED = 'HandDetected'
HIGHCONFIDENCE = 'HighConfidence'
HANDPOSITION_X = 'HandPosition_x'
HANDPOSITION_Y = 'HandPosition_y'
HANDPOSITION_Z = 'HandPosition_z'
HANDROTATION_X = 'HandRotation_x'
HANDROTATION_Y = 'HandRotation_y'
HANDROTATION_Z = 'HandRotation_z'
HANDVELOCITY_X = 'HandVelocity_x'
HANDVELOCITY_Y = 'HandVelocity_y'
HANDVELOCITY_Z = 'HandVelocity_z'
WRISTTWIST = 'WristTwist'
ISPINCHGRABBING = 'IsPinchGrabbing'
ISPALMGRABBING = 'IsPalmGrabbing'
ISAUTOGRIPGRABBING = 'IsAutogripGrabbing'
STRENGTHTHUMBINDEX = 'StrengthThumbIndex'
STRENGTHTHUMB_MIDDLE = 'StrengthThumbMiddle'
STRENGTHTHUMB_RING = 'StrengthThumbRing'
STRENGTHTHUMB_PINKY = 'StrengthThumbPinky'
STRENGTHPALM_INDEX = 'StrengthPalmIndex'
STRENGTHPALM_MIDDLE = 'StrengthPalmMiddle'
STRENGTHPALM_RING = 'StrengthPalmRing'
STRENGTHPALM_PINKY = 'StrengthPalmPinky'
NUMREPETICION = 'NumRepeticion'


## FATIGAS
FATIGA_WRIST = 'Fatiga_Wrist'
FATIGA_STRENGTH = 'Fatiga_Strength'
FATIGA_TIEMPO = 'Fatiga_Tiempo'
FATIGA_VELOCIDAD = 'Fatiga_Velocidad'
FATIGA_HEADPOSITION = 'Fatiga_HeadPosition'

### PESOS OWA
OWA_TIEMPO = 0.2
OWA_VELOCIDAD = 0.2
OWA_HEADPOSITION = 0.3
OWA_STRENGTH = 0.3

#AUXILIARES
MAX_HP_X = 'MAX_HEADPOSITION_X'
MIN_HP_X = 'MIN_HEADPOSITION_X'
MAX_HP_Y = 'MAX_HEADPOSITION_Y'
MIN_HP_Y = 'MIN_HEADPOSITION_Y'
MAX_HP_Z = 'MAX_HEADPOSITION_Z'
MIN_HP_Z = 'MIN_HEADPOSITION_Z'