import Constantes.Constantes as Const

OWA_TIME = 0.2
OWA_VELOCITY = 0.1
OWA_HEADPOSITION = 0.2
OWA_STRENGTH = 0.3
OWA_HAND_TRAJECTORY = 0.2
PENALIZATION_VALUE_BLOCK_DROP = 0.15
PENALIZATION_VALUE_INCORRECT_MOVEMENT = 0.1


FATIGUE_METRICS_BBT = {
    Const.FATIGUE_STRENGTH: OWA_STRENGTH, 
    Const.FATIGUE_TIME: OWA_TIME,
    Const.FATIGUE_VELOCITY: OWA_VELOCITY, 
    Const.FATIGUE_HAND_TRAJECTORY: OWA_HAND_TRAJECTORY,
    Const.FATIGUE_HEADPOSITION: OWA_HEADPOSITION,
}
FATIGUE_PENALIZATIONS_BBT = {
    Const.PENALIZATION_BLOCK_DROP: PENALIZATION_VALUE_BLOCK_DROP,
    Const.PENALIZATION_INCORRECT_MOVEMENT: PENALIZATION_VALUE_INCORRECT_MOVEMENT
}

BBT_DURATION = 60    #Seconds